- ome_zarr.py
The image can still be opened if the metadata loading fails
> Move metadata code to load_omero_metadata

- ome_zarr.py
Unfortunately, `requests` doesn't (easily) handle local paths or the
file:// scheme. Instead, we perform a check and delegate to an
underlying implementation.
> Support local files

- README.rst
Add `pip install ome-zarr` to the README, and other tweaks.
> Pip install

- ome_zarr
- ome_zarr.py
cc: @jburel @will-moore 
```
./ome_zarr /tmp/my.zarr
```
> simple cli: provider helper helpers for non napari usage

- ome_zarr.py
> download: exit early if not an ome-zarr

- .travis.yml
* add option to deploy via travis when a tag is pushed
Settings in travis have been set
> deploy via travis

- LICENSE
- README.rst
- setup.py
Move to BSD license and migrate @jburel's change from https://github.com/ome/ome-zarr-py/pull/12.
> README & LICENSE

- README.rst
Add a bit more info to REAME:
- mention ome-zarr spec with link
- output option for download
> Add to README

- ome_zarr.py
> omit 'channel_axis' for non-ome_zarrs (fix #25)

- ome_zarr.py
See issue : https://github.com/ome/ome-zarr-py/issues/32#issue-664496745
All tests pass, but I had to make the napari reader check for a ```None``` because checking only for```instance.is_zarr()``` errored when the file path returns a ```None```. when parse_url instance returns None as it does with ```"fake.file"``` in the test.
> add check for directory for LocalZarr for Windows compatability 

- .github/workflows/tag.yml
- .github/workflows/windows.yml
* Fix naming in windows.yml
* Test auto-tagging in tag.yml
> Action improvements

- .github/workflows/precommit.yml
- .github/workflows/windows.yml
- .pre-commit-config.yaml
- ome_zarr.py
- ome_zarr_cli.py
- setup.py
- tests/create_test_data.py
- tests/test_ome_zarr.py
Adds black autoformatter, flake8, yamllint.
Also adds commented config for mypy since there are some type hints but they need to be fixed.
Best reviewed one commit at a time.
> Add Precommit for linting

- ome_zarr.py
e.g.
```
{"image":{"array":"../../0/"},"color":{"true":-2139062144}}
```
see https://github.com/ome/omero-ms-zarr/pull/60
See https://github.com/intake/filesystem_spec/issues/342#issuecomment-654314336
> mask fault-tolerance (Proposed 0.0.12)

- ome_zarr/data.py
- ome_zarr/reader.py
- tests/test_starting_points.py
see: https://github.com/ome/omero-ms-zarr/pull/71
> Implement new color suggestion

- .github/workflows/build.yml
- codecov.yml
- tests/test_napari.py
- tox.ini
Introduced in https://github.com/ome/ome-zarr-py/pull/51 but commented out due to the issues with getting the build working.
> Re-activate codecov

- .github/workflows/pre-releases.yml
Based on https://github.com/napari/napari/blob/master/.github/workflows/test_prereleases.yml with thanks to @Czaki
> pre-releases.yml: run tox with --pre periodically

- README.rst
> minor edit to test workflow

- README.rst
- docs/source/python.rst
Update docs to mention dask support.
Also add a code sample for reading data, since this is hard to figure out from the api docs alone.
> Dask docs update

- .pre-commit-config.yaml
- ome_zarr/axes.py
- ome_zarr/cli.py
- ome_zarr/csv.py
- ome_zarr/data.py
- ome_zarr/format.py
- ome_zarr/io.py
- ome_zarr/reader.py
- ome_zarr/utils.py
- ome_zarr/writer.py
- tests/test_writer.py
See https://github.com/ome/ome-zarr-py/pull/236
According to failing jobs log, followed https://github.com/hauntsaninja/no_implicit_optional
```
$ pip install no_implicit_optional
$ no_implicit_optional ome_zarr
Calculating full-repo metadata...
Executing codemod...
Finished codemodding 14 files!
- Transformed 14 files successfully.
- Skipped 0 files.
- Failed to codemod 0 files.
- 0 warnings were generated.
```
> Pre commit ci update config

- .codespellrc
- .github/workflows/codespell.yml
- .pre-commit-config.yaml
This project is one of the few which had no typo found by codespell  (congrats) but I decided to offer keeping that so "programmatically" ;)
> codespell: config + workflow + pre-commit

- CHANGELOG.md
@joshmoore OK to go ahead and release this?
> Changelog 0.8.0

- ome_zarr/dask_utils.py
There is no need to create a new tuple from a tuple.
> `factors` is already a tuple

- CHANGELOG.md
> changelog 0.8.2

- docs/source/python.rst
Follow up from https://github.com/ome/ome-zarr-py/pull/317
> fix layout

- .github/workflows/build.yml
- tox.ini
since Python 3.11 has been out for a while, I thought it was worth adding tests
> Add tests on python 3.11

- README.rst
Fixes https://github.com/ome/ome-zarr-py/issues/319
> Fix doc install instructions in README

- .github/workflows/build.yml
- .github/workflows/codespell.yml
- .github/workflows/dispatch.yml
- .github/workflows/pre.yml
- .github/workflows/precommit.yml
- .github/workflows/publish_pypi.yml
- .readthedocs.yml
Update action to run on ubuntu 22.04
> Gha update

- CHANGELOG.md
#261 was merged to master but never released. xlink with spatialdata https://github.com/scverse/spatialdata/pull/517
> add #261 to changelog

- ome_zarr/format.py
SIM910 Use `get(...)` instead of `get(..., None)`
> Apply some ruff/flake8-simplify rules (SIM)

- ome_zarr/csv.py
- ome_zarr/reader.py
- tests/test_starting_points.py
PERF401 Use a list comprehension to create a transformed list
> Apply some ruff/Perflint rules (PERF)

- CHANGELOG.md
Add changelog 0.11.0 - see https://github.com/will-moore/ome-zarr-py/blob/changelog_0.11.0/CHANGELOG.md
> Add changelog 0.11.0

- ome_zarr/format.py
> read_only if mode is 'r'
