ome/ome-zarr-py

README.rst
ome_zarr.py

Otherwise, check if a Zarr is just an array and if so, load it.
No handling of non-multiscale groups is currently supported.

is_ome_zarr: check for "multiscales" for resolution loading

---

README.rst
ome_zarr
ome_zarr.py
ome_zarr_cli.py
setup.py

To test:
NB: try with and without the ```--target test``` option
Would also be good to test on windows?
```
$ ./ome_zarr download 'https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/' --target test
image_id 6001240
datasets ['0', '1']
downloading to test/6001240.zarr
resolution 1...
[########################################] | 100% Completed | 13.8s
resolution 0...
[########################################] | 100% Completed | 18.8s
```
This should include the `.zattrs` and `.zgroup` files.
Also ```./ome_zarr info 'https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/' ``` (moved into info subcommand)

Download zarr

---

ome_zarr.py

Passing a pyramid of length 1 leads to the exception:
```
AttributeError: 'list' object has no attribute 'shape'
```
see: https://github.com/napari/napari/issues/1225

Workaround pyramids of length 1

---

setup.py

I installed the dev version in conda env 
Tried to run 
```
ome_zarr download https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/
```
This returns
```
No module named 'pluggy'
```
This PR adds ``pluggy`` as a dependency

missing dependencies

---

tests/create_test_data.py
tests/test_ome_zarr.py

Since we now store omero metadata in the zarr attrs, we have access to this data after download.
Updating the test image creation and the tests accordingly.

Test image use zattrs for omero

---

ome_zarr.py

Likely will need to move to throwing exceptions and setting return codes soon (_a la_ yaclifw)
cc: @sbesson

download: exit early if target exists (fix #14)

---

ome_zarr.py

Thanks to @tlambert03 and https://github.com/napari/napari/pull/1219, starting the plugin with a bad URL showed much more information about what went wrong. With this PR, we catch the exception and log it at `WARNING` which is _not_ shown to the user by default:
```
(py36) /opt/ome-zarr-py $napari http://localhost:8080/idr/zarr/v0.1/151.zarr
11:32:27 ERROR PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
Cause was: ValueError('Not a zarr dataset or group: http://localhost:8080/idr/zarr/v0.1/151.zarr',)
in file: /opt/anaconda/envs/py36/lib/python3.6/site-packages/napari/utils/io.py
at line: 272
package: napari
version: 0.3.1
11:32:27 WARNING No plugin found capable of reading 'http://localhost:8080/idr/zarr/v0.1/151.zarr'.
11:32:27 ERROR (1) error occured in plugins: …
```

better error handling

---

.travis.yml
ome_zarr.py
setup.py

In addition to the switch from pluggy in https://github.com/ome/ome-zarr-py/pull/18 (thanks @tlambert03) this also makes the napari requirement optional.

Replace pluggy with optional napari_plugin_engine

---

ome_zarr.py

Currently supports opening of local zarr masks.
To test:
- Export masks as described in https://github.com/ome/omero-cli-zarr/pull/11
- Open image in napari e.g. ```$ omero napari view Image:5514375```
- In `napari` console, do ```viewer.open('path/to/5514375.zarr/masks/')```

Support opening of masks

---

README.rst
ome_zarr.py
ome_zarr_cli.py

To not swallow exceptions, `-v` (or more) can be used to
switch from WARN logging to DEBUG logging where the details
of the exceptions mentioned by @ngladitz are now printed.

Add --verbose option to CLI (fix #26)

---

ome_zarr.py

see: https://github.com/ome/omero-ms-zarr/issues/59

Rename 'masks' group to 'labels'

---

.github/workflows/windows.yml
ome_zarr/io.py
ome_zarr/reader.py
ome_zarr/utils.py
tests/test_cli.py

Removes the `zarr_path` variable from BaseZarrLocation, using a
pathlib.Path field in LocalZarrLocation and a URL string in
RemoteZarrLocation to properly handle the creation of subpaths across
multiple platforms. In general, use of os.path and especially
os.path.join should be avoided in favor of delegating to methods on the
zarr location objects.

Cross-platform path handling

---

.bumpversion.cfg
setup.py

I was unable to use `ome_zarr` when installating through PiPy (`pip install ome_zarr`) or locally `pip install .`:
```bash
% ome_zarr 
Traceback (most recent call last):
File "/Users/eric/nobackup/jax/ENV/bin/ome_zarr", line 5, in <module>
from ome_zarr.cli import main
ModuleNotFoundError: No module named 'ome_zarr'
```
Developer mode works fine (`pip install -e .`) as this creates the required link (`ENV/lib/python3.8/site-packages/ome-zarr.egg-link`.)
Reproducible with python3.8 under ubuntu 20.04 (docker) and MacOS with a clean virtualenv.
One work around is to use `packages`. I don't know why `py_modules` is insufficient.

Include packages in setup.py

---

setup.py

`pip install --upgrade napari` on Python 3.6 attempts
to update tifffile to versions which require Python 3.7+

Pin tifffile<2020.09.22 on Python 3.6

---

setup.py

This will help napari discover this package as a plugin from the UI, among other things.
Ref:
https://github.com/pypa/trove-classifiers/pull/53

Add Framework :: napari trove classifier to setup

---

setup.py
tests/test_napari.py

See https://github.com/ome/ome-zarr-py/pull/57#issuecomment-718708701
This attempts at solving the compatibility issue by adding environment markers to `extra_require`.

Cap napari extra requirement depending on the Python version

---

.github/workflows/posix.yml
.github/workflows/windows.yml
ome_zarr/data.py
ome_zarr/napari.py
ome_zarr/reader.py
tests/test_napari.py

Add support for label properties of the form
```
"properties": [
{
"label-value": 1,
"class": "Urban",
"m2": "100"
},
{
"label-value": 2,
"class": "Water",
"m2": "200"
},
{
"label-value": 3,
"class": "Deciduous Woody Horticulture"
},
{
"label-value": 4,
"class": "Evergreen Woody Horticulture"
},
...
```
as discussed in #60 .
Read these properties in as dictionary of `label-value` to properties.
Transform these properties in the napari reader to:
```
{
"index": [
1,
2,
3,
4,
...
],
"class": [
"Urban",
"Water",
"Deciduous Woody Horticulture",
"Evergreen Woody Horticulture",
...
],
"m2": [
"100",
"200",
"None",
"None",
"None",
...
]
}
```
This is the very first pass, so would appreciate feedback on the general approach before I move on to updating spec, documentation, tests, etc.
We probably …

Add support for label properties in zattrs and plugin

---

.github/workflows/posix.yml
.github/workflows/windows.yml
README.rst
ome_zarr/cli.py
ome_zarr/csv.py

Takes a csv file with 1 row per Mask (e.g. exported from OMERO with `Batch_ROI_Export`) and uses it to
add properties to the labels metadata in `ome-zarr`.
You need to specify which column of the csv contains an ID that matches a specified ID of each properties dict.
E.g. if you have exported labels from OMERO with https://github.com/ome/omero-cli-zarr/pull/50 then each properties dict will have e.g. `"omero:shapeId": 123` and this will correspond to the `shape_id` column of the Batch_ROI_Export.csv.
You also want to specify columns from the csv to use, e.g. `"area (pixels),X,Y,Width,Height"`.
You can also specify the column types (as in https://github.com/ome/omero-metadata/) to specify the data-type for each column (string by default).
- `d`: `DoubleColumn`, for floating point numbers
- …

csv to label properties

---

ome_zarr/napari.py
ome_zarr/reader.py

Show labels (under each image in a Plate) as a stitched layer on the plate:
@joshmoore I had to do a bunch of hacks here to work around the existing hierarchy traversal, since `Plate` and `PlateLabels` are 2 specs based on the same path/to/plate.zarr location.
Maybe I'm thinking this through the wrong way and there's a cleaner way you can think of?

show labels on plate

---

.github/workflows/zarr-dev.yml

Only on linux and a single version of Python.
This would help to catch potential regressions.

Add testing of Zarr development branch

---

environment.yml
ome_zarr/scale.py

The first scale of the label was uint16 while following
levels were floating point:
```
cat 6001237.zarr/labels/masks/*/.zarray | grep dtype
"dtype": "<i8",
"dtype": "<f8",
"dtype": "<f8",
"dtype": "<f8",
"dtype": "<f8",
```
cc: @will-moore @tischi

Fix labels of differing dtype

---

.isort.cfg
ome_zarr/data.py
ome_zarr/io.py
ome_zarr/reader.py
ome_zarr/scale.py
ome_zarr/utils.py
ome_zarr/writer.py
tests/test_writer.py

With the improvements to zarr.store.FSStore, all URLs can
be handled uniformly without needing to use `requests`. A
next step may in fact be to remove the ZarrLocation types.
This change does not yet support v0.2 and v0.1 at the same
time.

Update to v0.2 (nested storage) with FSStore

---

.github/workflows/build.yml
.github/workflows/pre.yml
.github/workflows/zarr-dev.yml
.isort.cfg
ome_zarr/reader.py
requirements/requirements-dev.txt
requirements/requirements-test.txt
setup.py
tox.ini

After the extraction of the napari plugin to `napari-ome-zarr`,
a number of the matrix builds can be eliminated. This PR attempts
to drop any dependencies on Qt-related code which should all be in
the plugin repository.

Cleanup builds

---

README.rst
tests/test_cli.py

See https://forum.image.sc/t/hcs-ome-zarr-data-unable-to-download/57114/6
The current S3 URLs are regularly hitting 503 errors which might be related to the fact these resources are being EOL'ed.
The three  OME-Zarr samples have been sync'ed to the new Embassy Cloud v4 storage.
Opening this PR as a prererequisite of the overall migration

Update Embassy URLs to use new Embassy Cloud object storage

---

ome_zarr/io.py
ome_zarr/reader.py

This is on top of #108 (attempt to fix HCS data viewing in v0.3 spec).
However, I have also just observed that the fixes in that PR are also needed for displaying labels with:
```
napari https://minio-dev.openmicroscopy.org/idr/v0.3/idr0062-blin-nuclearsegmentation/6001247.zarr
```
The extra commit on this branch is a cleanup of support for some HCS data generated before v0.1 (containing 'acquisitions').
It would be good to have labels working again in a release, to use as a public example at https://forum.image.sc/t/prepping-and-including-roi-masks/48750/17

Fix hcs 96

---

ome_zarr/writer.py
tests/test_writer.py

Fixes #122
This uses @constantinpape code from https://github.com/ome/ome-ngff-prototypes/blob/05b55d2516941e2eaf8fa82b722cad4371f99b5f/single_image/prototypes/v03.py#L19 to validate axes.
Also adds the required dimension order to the docstring for `write_image()` and `write_multiscale()`
cc @k-dominik 
To test, try the code sample below: https://github.com/ome/ome-zarr-py/pull/123#issuecomment-949691217 as it is, and with various shapes and valid/invalid axes. (invalid axes are not in the `tczyx` order, e.g. `xyz`. This should throw an `AssertionError`).
NB: This previously failed to scale with unhelpful error message (since the sizeX is 1), but error should now be improved.

Validate axes for writer

---

ome_zarr/writer.py
tests/test_writer.py

While investigating the testing requirements for https://github.com/ome/ome-zarr-py/pull/148, I found that my primary need are API helper methods allowing to write NGFF metadata e.g. `write_plate_metadata`, `write_well_metadata` and generate test data
As a first step towards these APIs, this PR refactors the existing multiscales generation code and extract the `multiscales` metadata addition logic into a separate API `write_multiscales_metadata`.
A direct application of this method is the scenario where a library would have its own implementation of the data writing but would still like to write the metadata using the core API. An example is `omero-cli-zarr` where https://github.com/ome/omero-cli-zarr/blob/7589cc47920b912480b3e6daa282c3d773c2bfdf/src/omero_zarr/raw_pixels.py#L276-L289 …

Add new API to write multiscales metadata

---

.github/workflows/build.yml
ome_zarr/format.py
ome_zarr/writer.py
tests/test_node.py
tests/test_reader.py
tests/test_writer.py

Follow-up of #149, this adds two new top-level APIs to the `ome_zarr.writer` module: `write_plate_metadata` and `write_well_metadata` for creating [plate](https://ngff.openmicroscopy.org/latest/#plate-md) and [well](https://ngff.openmicroscopy.org/latest/#well-md) specifications.
Unit tests are added to cover the combinations of parameters both in writing mode (`test_writer`) as well as in writing/reading mode (`test_node/test_reader`). This should significantly increase the coverage of the HCS codepath especially in `reader.py`.
The `test_plate_2D5D` unit test reproduces the issue raised in #145 and is currently marked as `xfail`. As the bug should be addressed in #148, I would propose to prioritize the review and integration of this PR first and remove the test marker in #148 together …

Add API for writing HCS metadata

---

ome_zarr/axes.py
ome_zarr/format.py
ome_zarr/reader.py
ome_zarr/writer.py
tests/test_writer.py

This builds on top of #123 to add validation of new axes dicts, based on the axes types.
Based on spec at https://github.com/ome/ngff/pull/57 (not merged yet).
There is a fair bit of validation code here cc @glyg 
Breaking changes:
- reader `axes` now returns a list of dicts instead of list of str
- OME-Zarr data is written as v0.4
But the writing API isn't breaking. Anything that was valid for v0.3 is also valid for v0.4, since we automatically add `type` info for `tczyx` dimensions.

Validate axes types v0.4

---

ome_zarr/writer.py
tests/test_writer.py

Follow-up of https://github.com/ome/ome-zarr-py/pull/153, this adds support for wells specified as lists of dictionaries rather than lists of string. The primary use case are:
1- support additional custom metadata e.g.
```
wells = [
{"path": "A/1", "concentration": "1"},
{"path": "A/2", "concentration": "2"},
{"path": "B/1", "concentration": "5"},
]
write_plate_metadata(self.root, ["A", "B"], ["1", "2"], wells)
```
2- support the upcoming breaking changes proposed in https://github.com/ome/ngff/pull/24 i.e.
```
wells = [
{"path": "A/1", "rowIndex": 0, "columnIndex": 0},
{"path": "A/2", "rowIndex": 0, "columnIndex": 1},
{"path": "B/1", "rowIndex": 1, "columnIndex": 0},
]
write_plate_metadata(self.root, ["A", "B"], ["1", "2"], wells)
```
Unit tests are updated accordingly to cover all …

Add support for passing wells as List[dict] in write_plate_metadata

---

ome_zarr/format.py
ome_zarr/writer.py
tests/test_node.py
tests/test_writer.py

Implements the specification changes proposed in https://github.com/ome/ngff/pull/24
- `rows` and `columns` must have unique names and be alphanumerical
- `wells` elements must include `path` (composed of exactly 2 groups), `rowIndex` and `colIndex`
As discussed in #157, the internal logic is adjusted to support the simple case of passing wells as list of strings and compute the row/column indices assuming the paths match the `rows` and `columns` lists.
Unit tests are updated to cover both the new and the legacy behavior as well as various invalid cases. The reader is not adjusted to consume the new logic. I would propose to complete the work on #148 first.

Add support for HCS 0.4 specification

---

ome_zarr/format.py
ome_zarr/reader.py
tests/test_node.py

Fixes #145 
A few specifications especially in the HCS domain still rely on the expectation that the underlying image will be 5D. As this constraint has been lifted with v0.3, these changes update various places in the code to dynamically identify the x, y and c axis before performing array manipulation.
Without this PR, both `ome_zarr info` and `napari` should fail to read https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/idr0094A/7751.zarr is a suitable example for testing this change (plate with XY dimensions). With this PR included, both commands should work successfully.
The last commits also disable `PlateLabels` to fix the HCS display in `napari`.  #177 as well as https://github.com/ome/ome-zarr-py/issues/65#issuecomment-1010074621 might be fixed by this PR

Fix remaining assumptions on 5D dimensions

---

ome_zarr/format.py
ome_zarr/reader.py
ome_zarr/writer.py
tests/test_writer.py

As discussed at https://github.com/ome/omero-cli-zarr/pull/93#discussion_r791685798
this allows the 'paths` argument of `write_multiscales_metadata()` to take a list of `datasets` dicts.
EDIT: Also updated to validate latest 0.4 spec with `coordinateTransformations` of `scale` and `translation`.

write_multiscales_metadata no_transformations

---

ome_zarr/format.py
ome_zarr/writer.py
tests/test_writer.py

Follow-up of the discussion in #162, this PR primarily the `write_multiscales_metadata` API introduced in #149 to only work on `datasets` passed as list of dictionaries. The writer unit tests are all adjusted for different version of the OME-NGFF format.
Additional unit tests are also added testing various combinations of valid and invalid `coordinateTransformations`. The transformations validation method is updated to add a few extra checks on the presence of mandatory keys.

Multiscales metadata API: only support datasets as lists of dictionaries

---

.isort.cfg
ome_zarr/writer.py
tests/test_writer.py

this proposes a change to the write_image api to allow compressors.  this is now more general to pass any options to the create dataset function and should handle multilevel options.
closes #160

add compressor option to write image

---

CHANGELOG.md

Following a discussion raised during today's OME meeting, this proposes to move towards the full release of `ome-zarr 0.3.0` with OME-NGFF 0.4 support.

Update CHANGELOG in preparation of 0.3.0 release

---

.github/workflows/build.yml

Attempt to upgrade after failure at https://github.com/ome/ome-zarr-py/pull/178/#issuecomment-1076958421:
```
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
Upstream issue: https://github.com/codecov/codecov-action/issues/557

Update to codecov action v2

---

.github/workflows/build.yml
ome_zarr/writer.py
tests/test_writer.py

Fixes #176 and #171
This PR:
- unifies `**metadata` across `write_image`, `write_multiscale` and `write_multiscales_metadata`
- introduces new convenience function `write_multiscale_image_labels` to create `image-label` data. 
For a usage example see https://github.com/ome/ome-ngff-prototypes/blob/update-ome-zarr-py/workflows/spatial-transcriptomics-example/convert_transcriptomics_data_to_ngff.py.
Still TODO:
I will address the TODOs if we decide to go forward with these changes.
Side-note: some confusing / unclear things I noticed in the `image-labels` spec while working on this.

Add image-label convenience functions

---

CHANGELOG.md
docs/source/python.rst
ome_zarr/data.py
ome_zarr/writer.py
tests/test_writer.py

This PR updates the signatures of `write_image`, `write_multiscale` and `write_multiscale_labels`:
- Removes `byte_order` from `write_image`: this was not used at all
- Removes `chunks` from all of them to avoid duplication with `storage_options`. 
- Moves `retuple` from `write_image` to `write_multiscale`, which is where the "actual" writing of data happens.
If we agree on these changes I will also add `write_labels` here (corresponding to `write_image`, but for image label data).
cc @will-moore @sbesson @joshmoore

Update write_image signature

---

.pre-commit-config.yaml
docs/source/conf.py
ome_zarr/writer.py

This proposes to use the standard docstring markup (`param`, `type`) to unify the rendering in the published documentation. Also includes the `deprecated` markup for deprecated options.
Initially applied to `write_multiscales` for a first round of review, the other docstrings in the `writer` module can be unified if we all agree with this strategy.
Proposed tag:  this is no a blocker for the imminent release of `0.4.0`  and should be releasable as a `0.4.1`

Convert `ome_zarr.writer.write_multiscale` to use docstrings markup

---

ome_zarr/format.py
ome_zarr/io.py

The call graph that led to duplicated WARNING messages of the form:
```
WARNING:ome_zarr.io:version mismatch: detected:FormatV02, requested:FormatV04
WARNING:ome_zarr.io:version mismatch: detected:FormatV04, requested:FormatV02
```
where caused by (roughly) this sequence of calls:
* Multiscales created using the default CurrentFormat (V04)
* Metadata of Multiscales is checked (V02) leading to the first warning
* The call to `zarr.create("labels")` initializes a Labels object
* It has no metadata and so defaults to the CurrentFormat (V04)
* This then mismatches from the expected format (V02) leading to the second
We now simply require that a value is passed for when the object does not contain metadata.

Fix format warning duplication

---

ome_zarr/format.py

Some writers (like for the DANDI project) have stored
the versions as floating point values (e.g. `0.2`).
Though this won't be long-term sustainable, relaxing
the version identification at this point seems
unproblematic.
cc: @leekamentsky

Relax version detection

---

ome_zarr/format.py
ome_zarr/io.py
ome_zarr/reader.py

This fixes one bug with viewing older (v0.1) plates and resolves the long-standing limitation of only loading a single resolution level for plates. Now we load a dask pyramid.
- Bug-fix: When `Format` class checks for version, it only read the `multiscales` metadata and not the 'plate', so we defaulted to using the `CurrentFormat` for reading plates. This meant that the `dimension_separator` was `/` and so for `v0.1` plates which use `.` the data wasn't loaded. Also, the `matches()` check was duplicated in the `FormatV02` subclass that had different logging than the `FormatV01` subclass so that logging for a `plate` previously looked like this:
```
14:55:02 DEBUG 0.4 matches None?
14:55:02 DEBUG 0.3 matches None?
14:55:02 DEBUG 0.2 matches None?
14:55:02 DEBUG V01:None v. 0.1
```
This now …

Plate pyramids and version

---

.github/workflows/zarr-dev.yml

The upstream master branch has been merged into main and removed - see https://github.com/zarr-developers/zarr-python/pull/1033

Fix the Zarr development GH workflow following branch renaming

---

ome_zarr/writer.py
tests/test_writer.py

Discovered during the testing of https://github.com/ome/omero-cli-zarr/pull/107
The `write*label*` APIs introduced in #178 do not store the OME-NGFF specification version in the `image-label` attributes.
The changes proposed in this PR
- add a `fmt` optional parameter to `write_label_metadata`
- add the logic to store the format version in the `image-label` attributes
- updates the label writing tests to test the version metadata
I would be inclined this as a bug fix and would suggest to get it out as a patch release `0.4.3`. But strictly speaking, this adds an optional parameter to a public API and could be released as a minor version increment.

Write version attribute to image-label specification

---

ome_zarr/format.py

When trying to use `ome-zarr-py` I was getting an error thrown that complained about `aiobotocore.session.AioSession`'s `__init__` not having an `auto_mkdir` parameter, which I believe was being incorrectly passed to it. This PR fixes that by adding a condition to exclude `auto_mkdir` from `kwargs` when the path starts with `s3`, similarly to what is already done when the path starts with `http`.

Disable auto_mkdir when path begins with `s3`

---

ome_zarr/reader.py

Fixes https://github.com/ome/napari-ome-zarr/issues/36
This uses the `multiscales` "name" field to populate the `node.metadata["name"]` which is then used by `napari-ome-zarr` for the layer names.
To test, using the data provided on the issue above (https://oc.embl.de/index.php/s/yfwGLkFRHsopcug) and opened in `napari`, the name ("image") is used for each layer.

Use multiscales name for node metadata['name']

---

ome_zarr/scale.py
ome_zarr/writer.py
tests/test_writer.py

This replaces #197, fixing merge conflicts between that and master and adding tests (described on the PR).
It also fixes an invalid comment and fixes a warning:
```
/Users/wmoore/opt/anaconda3/envs/omeroweb/lib/python3.9/site-packages/zarr/creation.py:221: UserWarning: ignoring keyword argument 'array_key'
warn('ignoring keyword argument %r' % k)
```

Storage options copy

---

ome_zarr/writer.py

The current implementation breaks when providing a single dict for `storage_options`, because `options.pop("chunks",...)` on line 238 removes the key `chunks` from the original `storage_options` dict after the first iteration. This happens because `options` is an alias of `storage_options` instead of a deep copy. My change fixes this and provides the intended behavior (all pyramid levels follow the same chunking scheme if `storage_options` is provided as a dict.

bugfix in chunks when providing storage_options as dict

---

ome_zarr/scale.py
tests/test_writer.py

Fixes issue reported at https://github.com/ome/ome-zarr-py/issues/219#issuecomment-1231613397
The issue there was that the dask writing used `resize_image()` which calculated down-sizing using `ceil()` so the sizes of pyramids levels were `100, 50, 25, 13, 7` instead of `100, 50, 25, 12, 6` as for the non-dask data.
I updated `resize_image()` to use the same integer division for calculating new_shape as is used in the `def __nearest()` for non-dask data.
To test:
- run the sample script on issue above (using ome-zarr-py installed from this branch)
- check that the pyramid sizes are `100, 50, 25, 12, 6` for both the `debug0.zarr` (non-dask) and `debug1.zarr` (dask).
- The `coordinateTransforms` should also be the same for both

Use integer division for new_shape in resize_image

---

CHANGELOG.md

Add changelog 0.6.0.
Do we call this `0.6.0rc1`, or should we just go for `0.6.0` release?

Add changelog 0.6.0

---

README.rst

I've been programming against and looking into `ome-zarr` recently and couldn't unsee this typo (and also couldn't see any others), so I thought I'd submit a quick fix PR. Feel free to roll this into something else if desired. Hope this doesn't cause any undesired CI expense!

Fix sphinx package typo in README

---

ome_zarr/writer.py

Fixes the issue described here: https://github.com/ome/ome-zarr-py/issues/242.
Unfortunately I am not able to isolate the bug in a minimal working example. More discussion here: https://github.com/scverse/spatialdata/issues/111.

Bug fix io

---

ome_zarr/writer.py
tests/test_writer.py

Fixes #250 
Notes:
- I couldn't get pre-commit to work on my machine — some Poetry error? — so apologies if there's some formatting issues, will fix
- The tests will fail if zarr ever changes its defaults to no compression, but that seems like a small risk.

Use zarr default compressor by default

---

.github/workflows/build.yml
.github/workflows/dispatch.yml
.github/workflows/pre.yml
.github/workflows/precommit.yml
.github/workflows/publish_pypi.yml

Upgrade checkout action to v3 and setup-python to v4 to avoid deprecation warnings

Upgrade action

---

ome_zarr/data.py
ome_zarr/reader.py
tests/test_reader.py

See #258.
This removes the exception handling that was obscuring useful errors there.
E.g. edit a sample zarr to an invalid version, e.g. `"version": 0.5` then try to open in `napari`:
```
$ napari --plugin napari-ome-zarr /path/to/image.zarr
Traceback (most recent call last):
File "/Users/wmoore/opt/anaconda3/envs/SSBD/bin/napari", line 8, in <module>
sys.exit(main())
File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/__main__.py", line 570, in main
_run()
File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/__main__.py", line 344, in _run
viewer._window._qt_viewer._qt_open(
File "/Users/wmoore/opt/anaconda3/envs/ssbd/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 867, in _qt_open
self.viewer.open(
File …
```

Don't handle exception in Multiscales init()

---

.isort.cfg
ome_zarr/writer.py
setup.py
tests/test_writer.py

Please, consider this PR as a possible solution to #237. It is more convenient to let the user decide how to compute the dask delayed objects. This is certainly useful/optimal when we are working with large image datasets.

Optimize zarr multiscale writing based on #237

---

CHANGELOG.md

Corresponding to https://github.com/ome/ome-zarr-py/milestone/1

changelog entry for 0.7.0

---

ome_zarr/cli.py

requiring arguments breaks being able to use `main` as a python entry point. (this also breaks conda recipe currently as conda build tests the entry point)
It seems arguments to `main` are ... a testing feature here? For testing one could also manipulate `sys.argv`...

allow main with empty args

---

docs/source/cli.rst
ome_zarr/cli.py
ome_zarr/utils.py

I had another case where I pasted some python script to tell a user how to serve the local files so that they can be viewed in ome-ngff-validator etc. at https://github.com/ome/ome-zarr-py/issues/284
It occurred to me that I've done this a few times, so instead we should just ship the code.
This PR allows you to do:
```
$ ome_zarr view path/to/image.zarr
```
and it will serve that `path/to` directory with the correct CORS headers and open your browser at https://ome.github.io/ome-ngff-validator/?source=http://localhost:8000/image.zarr to view your data (and allow you to open it in vizarr etc).

View in validator

---

setup.py

Peg dependency `fsspec`'s minimum version to `0.8.0` to address https://github.com/ome/ome-zarr-py/issues/294.

Set minimum fsspec version

---

setup.py

In https://github.com/ome/ome-zarr-py/pull/301/files we needed to avoid the latest fsspec version `fsspec 2023.9.0` due to avoid https://github.com/fsspec/filesystem_spec/issues/1357 (also reported at https://github.com/ome/ome-zarr-py/issues/304).
The fix at https://github.com/fsspec/filesystem_spec/pull/1358 is merged and should be included in the next fsspec release so we only need to exclude the current release version.
This makes the corresponding change to setup.py

Exclude fsspec 2023.9.0

---

ome_zarr/reader.py
tests/test_reader.py

Fixes https://github.com/ome/ome-zarr-py/issues/248
The current code assumes image paths under a well always match field of view indices, especially that "0" exists. However, the NGFF spec allows alphanumeric paths.
This change looks up the actual image path from the first well. This should not have a performance impact since the first well's `.zattrs` is read anyways. It is still assumed all wells have the same first image path (which the previous code did as well). In that case, an array of zeros is read (as previously).

Avoid hard-coded field-of-view path "0"

---

.readthedocs.yml
ome_zarr/reader.py
tests/test_reader.py

Fixes #297
This fixes the issue above: The `get_tile()` already returns a dask array so it doesn't need to be wrapped in `dask.delayed()`.
Test using the code sample on the ticket above.

Fix compute() on plate grid

---

ome_zarr/reader.py

Fixes #263.
For sparse Plates with empty Wells, we shouldn't try to load empty Wells.
Here, we check if the Well exists first - and return zeros.
To test, try to open a sparse plate in napari, e.g.
```
$ napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0072B/9512.zarr
```
Should see no errors in the terminal.
*Without* this PR you get lots of errors like this...
```
Traceback (most recent call last):
File "/Users/wmoore/opt/anaconda3/envs/omeroweb2/bin/napari", line 8, in <module>
sys.exit(main())
File "/Users/wmoore/opt/anaconda3/envs/omeroweb2/lib/python3.9/site-packages/napari/__main__.py", line 551, in main
_maybe_rerun_with_macos_fixes()
File "/Users/wmoore/opt/anaconda3/envs/omeroweb2/lib/python3.9/site-packages/napari/__main__.py", line 539, in _maybe_rerun_with_macos_fixes …
```

Check Well exists before trying to load data

---

docs/source/intro.rst

Since `ome-zarr` is available on conda-forge, I thought it would be good to list that option in the installation instructions.

Add conda to installation options

---

ome_zarr/format.py

- Add a short docstring to `Format` explaining it's a base class.
- Fix formatting in `validate_coordinate_transformations`

Minor improvements to format docs

---

ome_zarr/io.py

Solves being unable to load HCS datasets on S3, GCP, or Azure, see this issue: https://github.com/ome/ome-zarr-py/issues/321.

fix reading HCS datasets at cloud paths https://github.com/ome/ome-zarr-py/issues/321

---

.github/workflows/build.yml

Since tox creates a new environment and installs dependencies there, no need to install all the dependencies beforehand.

Only install required deps when testing

---

docs/source/python.rst

I personally found the first example encountered in the docs quite complicated. This PR simplifies it so it's a minimal working example of using the basic functionality of writing an ome-zarr file. I've then split up the extensions to the example (rendering settings and adding labels) to extra sections below, so someone new to ome-zarr-py can build up their code bit by bit instead of being overwhelmed by it all in one go.

Simplify first example in docs

---

.pre-commit-config.yaml
ome_zarr/data.py
ome_zarr/reader.py
ome_zarr/writer.py
tests/test_reader.py
tests/test_writer.py

close #260 .
Validation before write is minimal, feedbacks welcome.

add omero metadata to writer

---

.pre-commit-config.yaml
mypy.ini
ome_zarr/io.py

Replaces https://github.com/ome/ome-zarr-py/pull/293. I also removed the duplicate `mypy` hook.

Update and fix pre-commit

---

ome_zarr/io.py
requirements/requirements-dev.txt

In https://github.com/ome/ome-zarr-py/pull/338 I noticed that `fsspec` has been (accidentally??) pinned in the tests. Opening this PR to demonstrate that when it's unpinned the tests fail, indicating incompatibility with more recent versions of `fsspec`.

Unpin fsspec in dev requirements

---

ome_zarr/scale.py
ome_zarr/writer.py
tests/test_scaler.py

- Define property ``func`` to get downsample function.
- Use ``scaler.func`` instead of ``scaler.nearest`` in function ``_create_mip``.

Allow to change downsample function

---

.github/workflows/build.yml
.pre-commit-config.yaml

Following https://github.com/zarr-developers/zarr-python/pull/1647

Update to codecov 4

---

CHANGELOG.md
ome_zarr/writer.py
tests/test_writer.py

Fixes https://github.com/ome/ome-zarr-py/issues/364. I noticed there wasn't a changelog, so I added one, I hope that's okay? I think it's important to communicate bug fixes like this.

Fix scalar chunking

---

.isort.cfg
ome_zarr/io.py
tests/test_io.py

By supporting FSStore as input, more complex ZarrLocations are possible like private remote stores.

Support init of ome_zarr_py.io.ZarrLocation with zarr.storage.FSStore

---

docs/source/cli.rst

- Use bash highlighting
- Break up code blocks so it's easier to copy/paste commands
- Remove leading `$` so it's easier to copy/paste commands

Improve CLI docs

---

.github/workflows/build.yml
setup.py

numpy 2.0.0 has been released with breaking changes. Avoid installing till this can be reviewed etc.
Same as https://github.com/ome/omero-py/pull/414
cc @sbesson

Pin numpy<2 in setup.py

---

ome_zarr/writer.py
tests/test_writer.py

If writing a dask array and `compute = False`, the image metadata will be written even if some of the array chunks are not written successfully. This ensures that metadata is written only after all chunks are stored. Thanks.

Write metadata using delayed that depends on writing array(s)

---

.github/workflows/build.yml
.github/workflows/pre.yml
CHANGELOG.md
setup.py
tox.ini

As per [SPEC 0](https://scientific-python.org/specs/spec-0000/), don't need to support Python 3.8 or 3.9 any more. As per a comment below, I've only dropped support for 3.8 here.

Drop support for Python 3.8

---

setup.py

- I tested with the ruff plugin: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin
```
> ruff check . --select NPY201
All checks passed!
```
- I ran tests locally with numpy 2 and all pass
- I checked dependencies and everything seems good:
https://github.com/numpy/numpy/issues/26191
I think everything should be good to go?

Enable numpy 2 (lift pin in setup.py)

---

docs/source/python.rst

Because parse_url is called with mode="w", I found there's no need to manually create the directory first.

Simplify Python tutorial

---

setup.py

Trying to fix build at https://github.com/ome/ome-zarr-py/actions/runs/12038548002 which failed because Zarr v3 somehow got installed.

pin zarr at < 3

---

.pre-commit-config.yaml
ome_zarr/axes.py
ome_zarr/cli.py
ome_zarr/conversions.py
ome_zarr/csv.py
ome_zarr/dask_utils.py
ome_zarr/data.py
ome_zarr/format.py
ome_zarr/io.py
ome_zarr/reader.py
ome_zarr/scale.py
ome_zarr/types.py
ome_zarr/utils.py
ome_zarr/writer.py
setup.py
tests/test_cli.py
tests/test_starting_points.py
tests/test_writer.py

This updates the version of pyupgrade to match the minimum supported version of the package, and makes the corresponding pyupgrade fixes.

Update version of pyupgrade

---

ome_zarr/scale.py

Fixes https://github.com/ome/ome-zarr-py/issues/409

Document Scaler attributes

---

.pre-commit-config.yaml
ome_zarr/axes.py
ome_zarr/cli.py
ome_zarr/csv.py
ome_zarr/data.py
ome_zarr/format.py
ome_zarr/io.py
ome_zarr/reader.py
ome_zarr/scale.py
ome_zarr/types.py
ome_zarr/writer.py
tests/test_writer.py

Consistent with:
https://github.com/ome/ome-zarr-py/blob/14f407f15205025e45d8288eecf1ca07a0c9e030/pyproject.toml#L17

Enable Python 3.10+ in pre-commit hooks

---

.pre-commit-config.yaml

https://github.com/asottile-archive/seed-isort-config is deprecated and has been archived in 2020:
> this is no longer needed as of `isort>=5`

`seed-isort-config` no longer needed as of `isort>=5`

---

.pre-commit-config.yaml

Using this mirror lets us use mypyc-compiled black, which is about 2x faster

Use the black mirror repository for pre-commit

---

ome_zarr/csv.py
ome_zarr/io.py
ome_zarr/writer.py
tests/test_reader.py
tests/test_upgrade.py
tests/test_writer.py

Apply ruff-specific rules (RUF)

---

.pre-commit-config.yaml
pyproject.toml

I don't think ruff has an equivalent to [flake8-rst-docstrings](https://github.com/peterjc/flake8-rst-docstrings).
Either keep it, or apply ruff rules releated to docs:
* [pydocstyle (D)](https://docs.astral.sh/ruff/rules/#pydocstyle-d)
* [pydoclint (DOC)](https://docs.astral.sh/ruff/rules/#pydoclint-doc)

flake8, isort → ruff

---

pyproject.toml

Hey, thanks for your work here!
I noticed that although `distributed` is listed in the dependencies, as far as I can tell the package is not being used in `ome-zarr-py`. So this PR removes it.
Next to cleaning up the dependencies, this can be useful for using `ome-zarr-py` within WASM-based environments (e.g. jupyter lite), which `distributed` is not compatible with.

Remove distributed from dependencies (unused)

---

ome_zarr/writer.py

This improves the implementation of `_create_mip()` by:
- Removing the `axes` return. This isn't needed, because `axes` is never modified within the function. This simplifies the return type.
- Add an `AxesType` alias that can be used across `writer.py` to prevent having to redefine the type in lots of function signatures
- Add a docstring to `_create_mip()`

Simplify _create_mip()

---

docs/source/cli.rst
ome_zarr/cli.py
ome_zarr/utils.py
tests/test_cli.py

With `$ ome_zarr view my_image.zarr` we can view a single zarr image (or plate etc) in the ome-ngff-validator by serving the image from a local python server.
But this PR allows you to browse a collection of images in your local filesystem with:
```
$ ome_zarr finder path/to/my_data_folder/
```
This command will traverse your local filesystem, looking for zarr images (only `.zattrs` for now - can add zarr v3 support as a follow-up) and collect them into a CSV. This CSV is then served by the localhost python server and opened in BioFile Finder, allowing you to browse your local zarr images which are also served in the same way (and see thumbnails, copy URL etc).
Then in Bio-File Finder, you can "Group By" > "Folders" and you'll get a "tree" of all your folders containing images.

View in biofile finder

---

.github/workflows/publish_pypi.yml
README.rst

Aims to fix publish to pypi as at https://github.com/ome/omero-py/pull/456
Last attempt failed at https://github.com/ome/ome-zarr-py/actions/runs/14590677576
Also updates release steps in README.

Pypi release v1

---

CHANGELOG.md

No change in released code, but I think the bump (and new tag) is still needed to trigger publishing to Pypi?

Changelog 0.11.1

---

.github/workflows/pre.yml

Merge of #413 with a dependency on zarr-python>=3.0.0 which is Python>=3.11 requires dropping the 3.10 build from the pre.yml job.
https://github.com/ome/ome-zarr-py/actions/runs/16799565898/job/47577538690

Drop 3.10 for pre-release build
